# Pirates Mastermind: CustomizeablePowers\Brawling\BuildUp_Activation.fx without the build up rings. Generated by pirates_gen.py.
#############################################################
## BuildUp_Activation.fx
#############################################################

FxInfo
Lifespan 150

#############################################################

Condition
	On 	Time
	Time	0
	Event
		Type	Local
		At	Root
		Sound 	Brawling_CombatReadiness_01 200 100 .8
	End
End

Condition
	On	Time
	Time	0

	Event
		Type	Start
		At	Root
		Bhvr	CustomizeablePowers/Brawling/Dust_Expanding.bhvr
		BhvrOverride
			PositionOffset	0.0 0.5 0.0
		End
		Part	CustomizeablePowers/Brawling/Hit_Smoke_Radial_Big.part
		Part	CustomizeablePowers/Brawling/Hit_Smoke_Radial_Lingering_Big.part
		Lifespan 90
	End

	Event
		Type 	Start
		At	Root
		BhvrOverride
			PositionOffset	0.0 0.25 0.0
		End
		Part	CustomizeablePowers/Brawling/Buildup_Shockwave.part
	End

	Event
		Type 	Start
		At	Root
	End
End

#############################################################

End