# Pirates Mastermind: WEAPONFX/LambdaTurrets/Shell_Hit.fx with our cannon sound. Generated by pirates_gen.py.
#############################################################
## Turret_MuzzleFlash.fx
#############################################################

FxInfo
LifeSpan 150

#############################################################

Condition
	On 	Time
	Time 	0

	Event
		Type	Local
		At	Origin
		Bhvr	behaviors\CameraShake01Subtle.bhvr
		BhvrOverride
			PositionOffset	0.0 0.2 0.0
		End
		Part	WEAPONFX/LambdaTurrets/Explosion_Flash_Large.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Shockwave_Small.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Streaks_Small.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Fire_Rings_Large.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Flash_Large_Flat.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Glow_Lingering_Flat.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Shockwave_Flat.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Glow_Flat.part
		Sound Pirates_Cannon_Shot 300 300 1
		Lifespan 4
	End

	Event
		Type	Local
		At	Origin
		Part	WEAPONFX/LambdaTurrets/Explosion_Streaks_Thin_Small.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Sparks_Small.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Smoke_Additive_Yellow.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Smoke_Lingering.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Smoke.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Rocks.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Smoke_Thin.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Fire_Rings_Small.part
		Part	WEAPONFX/LambdaTurrets/Explosion_Flash.part
		Lifespan 5
	End

	Event
		Type	Local
		At	Origin
		Part	WEAPONFX/LambdaTurrets/Coals_Flat_Additive.part
		Lifespan 1
	End

	Event
		Type	Local
		At	Origin
		BhvrOverride
			PositionOffset	0.0 -1.0 0.0
		End
		Part	WEAPONFX/LambdaTurrets/BurnPatch_Sparks.part
		Lifespan 30
	End
	Event
		Type	StartPositOnly
		At	Origin
		Bhvr	behaviors/CameraShake01.bhvr

		BhvrOverride
			PositionOffset	0.0 -3.0 0.0
		End
		Part	WEAPONFX/LambdaTurrets/Dust_Circle.part
		Part	WEAPONFX/LambdaTurrets/Dust_Circle_Lingering.part
		Part	WEAPONFX/LambdaTurrets/Dust_Shockwave.part
		Part	WEAPONFX/LambdaTurrets/Dust_Shockwave_Fill.part
		Lifespan	8
	End

	Event
		Type	StartPositOnly
		At	Origin
		BhvrOverride
			PositionOffset	0.0 8.0 0.0
		End
		Part	WEAPONFX/LambdaTurrets/Dust_Pillar.part
		Part	WEAPONFX/LambdaTurrets/Dirt_Pillar.part

		POther	DustAnchor
		Lifespan	5
	End
End

Condition
	On	Time
	Time	5

	Event
		Type	StartPositOnly
		At	Origin
		Bhvr	behaviors\Splat_RuneCircle.bhvr
		BhvrOverride
			Alpha		255
			FadeInLength	5
			FadeOutLength	80
			StartColor	20 20 20
			Scale		40.0 10.0 40.0
		End
		Splat	BlurredOilSplatDark.tga
		Lifespan 80
	End

	Event
		Type	StartPositOnly
		At	Origin
		Bhvr	behaviors\Splat_RuneCircle.bhvr
		BhvrOverride
			PositionOffset	0.0 0.1 0.0
			Alpha		200
			FadeInLength	5
			FadeOutLength	80
			StartColor	20 20 20
			Scale		40.0 10.0 40.0
		End
		Splat	Energy_ConeB3.tga
		Lifespan 100
	End



End