# Pirates Mastermind: the barrage timing of WEAPONFX/LambdaTurrets/Lambda_ArtilleryBarrage.fx. Generated by pirates_gen.py.
#############################################################
## Turret_MuzzleFlash.fx
#############################################################

FxInfo
LifeSpan 36

############################################################

Condition
	On	Time
	Time	0

	Event
		Type	Local
		At	Root
		BhvrOverride
			StartJitter	10 0 10
		End
		ChildFX	pirates/Cannon_Volley.fx
		Lifespan	30
	End
End

Condition
	On	Cycle
	Time	12

	Event
		Type	Local
		At	Root
		BhvrOverride
			StartJitter	10 0 10
		End
		ChildFX	pirates/Cannon_Volley.fx
		Lifespan	30
	End
End

#############################################################

End