# Pirates Mastermind: one cannon strike, the ship fires and the shot lands. Generated by pirates_gen.py.
FxInfo
	LifeSpan 150
Condition
	On Time
	Time 0
	Event
		Type Local
		At Root
		Sound Pirates_Cannon_Fire 200 200 1
	End
End
Condition
	On Time
	Time 12
	Event
		Type Local
		At Root
		ChildFx pirates/Cannon_Impact.fx
	End
End
End
