# Pirates Mastermind: the order to fire, two bells as the arm points. Generated by pirates_gen.py.
FxInfo
	LifeSpan 90
Condition
	On Time
	Time 35
	Event
		Type Local
		At Root
		Sound Pirates_Order_Bell 100 100 1
	End
End
End
