# Pirates Mastermind: the coin's sound as the thumb flicks it (frame 56 of the Flip Coin emote). Generated by pirates_gen.py.
FxInfo
	LifeSpan 150
Condition
	On Time
	Time 56
	Event
		Type Local
		At Root
		Sound Pirates_Coin_Flip 60 60 1
	End
End
End
