# Pirates Mastermind: ENEMYFX\V_Coralax\Coral_Guardian\Summon_Attack.fx without its sound. Generated by pirates_gen.py.
#########################################################

FxInfo
Flags	InheritAlpha
Lifespan 100

##########################################################

Condition
	On 	Time
	Time 	20

	Event
		EName 	Stonesickle05
		Type	local
		At	WepR


		Part2	POWERS\EarthControl\GenericEarthHandsDust.part
		Part3	POWERS\EarthControl\GenericEarthHandsDust2.part
		Part4	POWERS\EarthControl\GenericEarthHandsDustRocks.part
		Part	POWERS\EarthControl\GenericEarthHandsDustRocks2.part

		LifeSpan	55
	End

	Event
		EName 	Stonesickle05
		Type	local
		At	WepL


		Part2	POWERS\EarthControl\GenericEarthHandsDust.part
		Part3	POWERS\EarthControl\GenericEarthHandsDust2.part
		Part4	POWERS\EarthControl\GenericEarthHandsDustRocks.part
		Part	POWERS\EarthControl\GenericEarthHandsDustRocks2.part

		LifeSpan	55
	End
End

###############################################################################

End