# Pirates Mastermind: Dead_Men. Generated by pirates_gen.py.
FxInfo
	LifeSpan 120
Condition
	On Time
	Time 0
	Event
		Type Local
		At Root
		Sound Pirates_Dead_Men 100 100 1
	End
	Event
		Type Local
		At Root
		ChildFx ENEMYFX/Praetorian/Apparitions/Emerge_Activation.fx
	End
End
End
