# Pirates Mastermind: the Clubs card aura for Lady Luck. Generated by pirates_gen.py.
#############################################################
## Fireflies_Body.fx
#############################################################

FxInfo

#########################################################

Condition
	On	Cycle
	Time	20
	Repeat		1
	RepeatJitter	1

	Event
		Ename	GEO_Leaves
		Type	StartPositOnly
		At	Head
		ChildFX	pirates/Luck_Clubs_Cards.fx
		Lifespan	200
	End

End

#############################################################

End