# Pirates Mastermind: TidalForces.fx without the yellow power-up. Generated by pirates_gen.py.
#
FxInfo

	LifeSpan 75


###########################################################
Condition
	On 	Time
	Time	0
	Event
		Type	Local
		At	Root
		Sound 	WB_TidalForces 100 100 .8
	End
End

	Condition
		On Time
		Time 0

		Event
			At WepR
			Type Local
			EName mainAnchor
			Bhvr Behaviors/GenericParticleFade.bhvr
			Part CustomizeablePowers/WaterBlast/WaterShot_HandGlow.part
			Part CustomizeablePowers/WaterBlast/WaterBurst_DrawIn_Spray3.part
			Part CustomizeablePowers/WaterBlast/WaterShot_GlowStreaks3.part
			Part CustomizeablePowers/WaterBlast/WaterBall_DrawIn_Splatter3.part
			Part CustomizeablePowers/WaterBlast/WaterBall_Drips.part
			LifeSpan 60
		End

		Event
			At WepL
			Type Local
			EName mainAnchor
			Bhvr Behaviors/GenericParticleFade.bhvr
			Part CustomizeablePowers/WaterBlast/WaterShot_HandGlow.part
			Part CustomizeablePowers/WaterBlast/WaterBurst_DrawIn_Spray3.part
			Part CustomizeablePowers/WaterBlast/WaterShot_GlowStreaks3.part
			Part CustomizeablePowers/WaterBlast/WaterBall_DrawIn_Splatter3.part
			Part CustomizeablePowers/WaterBlast/WaterBall_Drips.part
			LifeSpan 60
		End

		Event
			At WepR
			Type PositOnly
			EName mainAnchor
			Bhvr Behaviors/GenericParticleFade.bhvr
			Part CustomizeablePowers/WaterBlast/Drips_Hand.part
		End

		Event
			At WepL
			Type PositOnly
			EName mainAnchor
			Bhvr Behaviors/GenericParticleFade.bhvr
			Part CustomizeablePowers/WaterBlast/Drips_Hand.part
		End

	End

	Condition
		On Time
		Time 0



	End

	Condition
		On Time
		Time 10


	End

	Condition
		On Time
		Time 20


	End

	Condition
		On Time
		Time 30


	End

End
