# Pirates Mastermind: the Captain's parrot squawks when it arrives. Generated by pirates_gen.py.
FxInfo
	LifeSpan 60
Condition
	On Time
	Time 0
	Event
		Type Local
		At Root
		Sound Pirates_Parrot 100 100 1
	End
End
End
