# Pirates Mastermind: Summon_Captain. Generated by pirates_gen.py.
FxInfo
	LifeSpan 120
Condition
	On Time
	Time 0
	Event
		Type Local
		At Root
		Sound Pirates_Summon_Captain 100 100 1
	End
	Event
		Type Local
		At Root
		ChildFx pirates/Coin_Flip.fx
	End
End
End
