# Pirates Mastermind: Summon_Deep. Generated by pirates_gen.py.
FxInfo
	LifeSpan 120
Condition
	On Time
	Time 0
	Event
		Type Local
		At Root
		Sound Pirates_Summon_Deep 100 100 1
	End
	Event
		Type Local
		At Root
		ChildFx pirates/Coral_Rise_NoSFX.fx
	End
End
End
